# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/twinborn/Documents/GitHub/Xilinx/vivado_hls/HLS_IBUFDS/pjt_vivado_hlsip/pjt_vivado_hlsip.srcs/sources_1/ip/count_toggle_0/count_toggle_0.xci
# IP: The module: 'count_toggle_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/twinborn/Documents/GitHub/Xilinx/vivado_hls/HLS_IBUFDS/pjt_vivado_hlsip/pjt_vivado_hlsip.srcs/sources_1/ip/count_toggle_0/constraints/count_toggle_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'count_toggle_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/twinborn/Documents/GitHub/Xilinx/vivado_hls/HLS_IBUFDS/pjt_vivado_hlsip/pjt_vivado_hlsip.srcs/sources_1/ip/count_toggle_0/count_toggle_0.xci
# IP: The module: 'count_toggle_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/twinborn/Documents/GitHub/Xilinx/vivado_hls/HLS_IBUFDS/pjt_vivado_hlsip/pjt_vivado_hlsip.srcs/sources_1/ip/count_toggle_0/constraints/count_toggle_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'count_toggle_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
